### ISSUE TITLE
Fiber instrument seems not working with nashorn

### ISSUE THREAD

**Issue by tesseract2048** [puniverse/quasar#85]
Hi, i am getting `**oops. problem with stacktrace can't be trusted` errors with compiled javascript (with nashorn):

Details of error:
```
[error] WARNING: Uninstrumented methods on the call stack (marked with **): 
[error] 	at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1590)
[error] 	at co.paralleluniverse.fibers.Fiber.verifySuspend(Fiber.java:1567)
[error] 	at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:117)
[error] 	at com.mycompany.photon.workflow.expr.Env.info(Env.java:98)
[error] 	at com.mycompany.photon.workflow.expr.Env.info(Env.java:35)
[error] 	at jdk.nashorn.internal.scripts.Script$\^eval\_.runScript(<eval>:1) **oops. problem with stacktrace can't be trusted
[error] 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:535) **oops. problem with stacktrace can't be trusted
[error] 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209) **oops. problem with stacktrace can't be trusted
[error] 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378) **oops. problem with stacktrace can't be trusted
[error] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:542) **oops. problem with stacktrace can't be trusted
[error] 	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:76) **oops. problem with stacktrace can't be trusted
[error] 	at jdk.nashorn.api.scripting.NashornScriptEngine$4.eval(NashornScriptEngine.java:630) **oops. problem with stacktrace can't be trusted
[error] 	at com.mycompany.photon.workflow.expr.Expr.apply(Expr.java:48) **oops. problem with stacktrace can't be trusted
```

The fiber is created before invocation of `Expr.apply`, thus all these methods are executed within a fiber.

It is running on OS X Yosemite 10.10.2, `Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)`, with `quasar-core` `0.6.2-jdk8`.

Any idea? Thanks.

**Comment by circlespainter** [comment]
It could be related to https://github.com/puniverse/quasar/issues/82 which is fixed in `master`'s tip. Could you try with the latter (the version will be `0.6.3-SNAPSHOT`)?

**Comment by tesseract2048** [comment]
Hi,

Tried with latest snapshot, the error messages are gone but errors remain:

```
[error] WARNING: Uninstrumented methods on the call stack (marked with **): 
[error] 	at co.paralleluniverse.fibers.Fiber.checkInstrumentation(Fiber.java:1604)
[error] 	at co.paralleluniverse.fibers.Fiber.verifySuspend(Fiber.java:1581)
[error] 	at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:117)
[error] 	at com.mycompany.photon.workflow.expr.Env.info(Env.java:98)
[error] 	at com.mycompany.photon.workflow.expr.Env.info(Env.java:35)
[error] 	at jdk.nashorn.internal.scripts.Script$\^eval\_.runScript(<eval>:1) **
[error] 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:535) **
[error] 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209) **
[error] 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378) **
[error] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:542) **
[error] 	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:76) **
[error] 	at jdk.nashorn.api.scripting.NashornScriptEngine$4.eval(NashornScriptEngine.java:630) **
[error] 	at com.mycompany.photon.workflow.expr.Expr.apply(Expr.java:48) **
```

**Comment by circlespainter** [comment]
Ok, now the frames missing instrumentation are shown. This message is normal since you're invoking through Nashorn which is not instrumented, and the whole call stack must be in order to use fibers.

Since Nashorn is 3rd-party code you cannot annotate it or change it to throw `SuspendExecution`, but you can still use `suspendables` and `suspendable-supers` to instrument its methods and you can find information about them here: http://docs.paralleluniverse.co/quasar/#advanced-fibers.

We currently don't have a Nashorn integration but adding it could be as easy as adding the right methods to those resources, so I suggest you try.

You'll need to add the calls shown by those messages to such files, using the first one for concrete calls and the second one for interface calls. You might need to have a look at Nashorn's code to tell apart in each case but `SuspendableScanner` can help a lot.

**Comment by circlespainter** [comment]
@tesseract2048 Can you share at least part of the code? I can help you looking into it.

**Comment by tesseract2048** [comment]
Hi,

Sorry for disappearance these days.
Turns out that Nashorn did not satisfied my requirements well, so I am basically switching to Rhino, and introducing fiber is no longer necessary (since Rhino has built-in continuation support since 1.7, this essentially solved the problem).


I've been able to rebuild a example that falls into this category, as follows:

```
public class ReproduceMain {

  static final String EngineName = "nashorn";

  static final ScriptEngine Engine = new ScriptEngineManager().getEngineByName(EngineName);

  // executor for simulation of async operations
  static final ExecutorService executor = Executors.newSingleThreadExecutor();

  public static class Env {

    // script will call this method
    @Suspendable
    public String capture() throws Exception {
      return new FiberAsync<String, Exception>() {

        @Override
        protected void requestAsync() {
          // this should actually be a real async operation, but it's okay for demonstration
          executor.submit(() -> asyncCompleted("completed"));
        }
      }.run();
    }

  }

  public static void main(String[] args)
      throws InterruptedException, SuspendExecution, ExecutionException {
    System.out.println(new Fiber() {
      @Override
      protected Object run() throws SuspendExecution, InterruptedException {
        // plug in an instance of Env
        Engine.getContext().setAttribute("env", new Env(), ScriptContext.ENGINE_SCOPE);
        try {
          return Engine.eval("env.capture()");
        } catch (ScriptException e) {
          e.printStackTrace();
          return null;
        }
      }
    }.start().get());
  }
}
```

**Comment by circlespainter** [comment]
Ok, so you're going to use first-class continuations in JavaScript if I understand correctly. In the script above though you're interpreting some basic JavaScript through an invocation of the engine in a fiber, and that script then invokes a suspendable method. Is there any issue with that, does that work without instrumentation verification warning?

**Comment by tesseract2048** [comment]
The above example did not work and shown identical warnings as in the original attempt.

Is there a chance that we can automatically infer which methods are to be instrumented?

**Comment by circlespainter** [comment]
Yes. Automatic instrumentation for Clojure is coming soon while for other JVM it'll require more time. There's `scanSuspendables` in `auto` mode in the meanwhile but I think it will not help without some manual hints in this case, as the engine selection is done at runtime.

Anyway, I have successfully added few `suspendables` and `suspendable-supers` as suggested by instrumentation verification warnings and I don't get them anymore but I get this instead:

~~~
Exception in thread "main" java.lang.NoClassDefFoundError: co/paralleluniverse/fibers/SuspendExecution
	at jdk.nashorn.api.scripting.NashornScriptEngineFactory.newEngine(NashornScriptEngineFactory.java:233)
	at jdk.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:163)
	at testgrp.Main.<clinit>(Main.java:28)
Caused by: java.lang.ClassNotFoundException: co.paralleluniverse.fibers.SuspendExecution
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
~~~

I'm not a Nashorn expert at all but it looks like the scripting engine at some point references the Java app classes (in order to execute the Java-implemented method in the script?) and it can't find them. Is there some special classloading mechanism in Nashorn? How can you tell it to consider Java classes?

**Comment by circlespainter** [comment]
@tesseract2048 Have you had a chance to take a look?

**Comment by tesseract2048** [comment]
Hi, 

Maybe explicitly specifying  `ClassLoader` will help, which is documented here:
http://cr.openjdk.java.net/~sundar/jdk.nashorn.api/8u40/javadoc/jdk/nashorn/api/scripting/NashornScriptEngineFactory.html#getScriptEngine-java.lang.ClassLoader-

**Comment by circlespainter** [comment]
No, unfortunately this doesn't seem to work either. The class loading fails upon engine creation, not later during execution.

**Comment by circlespainter** [comment]
@tesseract2048 Ok, I think I understand the matter now: Nashorn lives in JVM's boot class path. We're instrumenting Nashorn itself and instrumentation adds references to Quasar classes, which Nashorn classes won't be able to resolve unless Quasar too exists in the boot class path.

Here https://github.com/circlespainter/quasar-85 you can find a Maven project that makes your example work, so it is an initial Nashorn integration experiment you can start from as well. Apart from adding some `suspendables` and `suspendable-supers` (and allowing Quasar to instrument the JDK as well through `-Dco.paralleluniverse.fibers.allowJdkInstrumentation=true`), Quasar and its dependency Guava are added to the boot classpath too.

Instrumentation verification still complains about a strange `jdk.nashorn.internal.scripts.Script$\^eval\_.:program` method that indeed is not instrumented (I'll have a look at why) but since it's very likely a bridge method with no state whatsoever this is probably a non-issue.

**Comment by circlespainter** [comment]
@tesseract2048 Actually instrumenting `jdk.nashorn.internal.scripts.Script$\^eval\_.:program` works, the ASM checking visitor was just complaining about the strange name but it worked fine once I removed it. You can run the sample with `mvn clean compile dependency:properties exec:exec`. Does this approach work for you?

**Comment by circlespainter** [comment]
@tesseract2048 Any feedback? Closing soon, you can re-open if you still have issues.

**Comment by beders** [comment]
I was able to get some of my JavaScript code instrumented with this, but only with AoT.
Now in my case, I need to run JS code that is not known during compile time.
At some point that JS code will call an async function I'd like to use fibers for.
Is there any way I can convince Quasar to instrument new code on the fly?

**Comment by pron** [comment]
Quasar currently supports only Java, Kotlin and Clojure, though with some work you might have some luck integrating other languages (we're happy to receive contributions). In Java 9, it will _probably_ support any language running on the JVM without any additional effort.
